from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 358)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.in_edit = QtWidgets.QTextBrowser(self.centralwidget)
        self.in_edit.setObjectName("in_edit")
        self.horizontalLayout.addWidget(self.in_edit)
        self.in_btn = QtWidgets.QPushButton(self.centralwidget)
        self.in_btn.setObjectName("in_btn")
        self.horizontalLayout.addWidget(self.in_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.out_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.out_edit.setReadOnly(True)
        self.out_edit.setObjectName("out_edit")
        self.horizontalLayout_2.addWidget(self.out_edit)
        self.out_btn = QtWidgets.QPushButton(self.centralwidget)
        self.out_btn.setObjectName("out_btn")
        self.horizontalLayout_2.addWidget(self.out_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.sensitivity_settings = QtWidgets.QSpinBox(self.centralwidget)
        self.sensitivity_settings.setMinimum(1)
        self.sensitivity_settings.setObjectName("sensitivity_settings")
        self.horizontalLayout_3.addWidget(self.sensitivity_settings)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.indent_settings = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.indent_settings.setMinimum(0.05)
        self.indent_settings.setMaximum(2.0)
        self.indent_settings.setSingleStep(0.01)
        self.indent_settings.setObjectName("indent_settings")
        self.horizontalLayout_4.addWidget(self.indent_settings)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.step_settings = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.step_settings.setMinimum(0.05)
        self.step_settings.setMaximum(2.0)
        self.step_settings.setSingleStep(0.01)
        self.step_settings.setObjectName("step_settings")
        self.horizontalLayout_5.addWidget(self.step_settings)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.info_btn = QtWidgets.QPushButton(self.centralwidget)
        self.info_btn.setObjectName("info_btn")
        self.verticalLayout_5.addWidget(self.info_btn)
        self.default_btn = QtWidgets.QPushButton(self.centralwidget)
        self.default_btn.setObjectName("default_btn")
        self.verticalLayout_5.addWidget(self.default_btn)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.use_presets = QtWidgets.QCheckBox(self.centralwidget)
        self.use_presets.setObjectName("use_presets")
        self.verticalLayout_6.addWidget(self.use_presets)
        self.presets = QtWidgets.QComboBox(self.centralwidget)
        self.presets.setEnabled(True)
        self.presets.setObjectName("presets")
        self.verticalLayout_6.addWidget(self.presets)
        self.edit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_btn.setObjectName("edit_btn")
        self.verticalLayout_6.addWidget(self.edit_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.automatization_btn = QtWidgets.QPushButton(self.centralwidget)
        self.automatization_btn.setObjectName("automatization_btn")
        self.gridLayout.addWidget(self.automatization_btn, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Content Mate"))
        self.label.setText(_translate("MainWindow", "Выберете файл (-ы) для обработки:"))
        self.in_btn.setText(_translate("MainWindow", "Выбрать файл (-ы)"))
        self.label_2.setText(_translate("MainWindow", "Выберете папку для сохранения результатов:"))
        self.out_btn.setText(_translate("MainWindow", "Выбрать папку"))
        self.start_btn.setText(_translate("MainWindow", "Начать обработку"))
        self.label_9.setText(_translate("MainWindow", "Настройки обработки видео: "))
        self.label_5.setText(_translate("MainWindow", "Чувствительность"))
        self.label_6.setText(_translate("MainWindow", "%"))
        self.label_4.setText(_translate("MainWindow", "Отступ"))
        self.label_8.setText(_translate("MainWindow", "сек."))
        self.label_3.setText(_translate("MainWindow", "Шаг"))
        self.label_7.setText(_translate("MainWindow", "сек."))
        self.info_btn.setText(_translate("MainWindow", "Инфо"))
        self.default_btn.setText(_translate("MainWindow", "По умолчанию"))
        self.use_presets.setText(_translate("MainWindow", "Использовать пресеты"))
        self.edit_btn.setText(_translate("MainWindow", "Настройки"))
        self.automatization_btn.setText(_translate("MainWindow", "Автоматизация"))
