from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 283)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.picture = QtWidgets.QLabel(Form)
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.horizontalLayout.addWidget(self.picture)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.in_edit = QtWidgets.QLineEdit(Form)
        self.in_edit.setReadOnly(True)
        self.in_edit.setObjectName("in_edit")
        self.verticalLayout.addWidget(self.in_edit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.out_edit = QtWidgets.QLineEdit(Form)
        self.out_edit.setReadOnly(True)
        self.out_edit.setObjectName("out_edit")
        self.verticalLayout_2.addWidget(self.out_edit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.star_btn = QtWidgets.QPushButton(Form)
        self.star_btn.setObjectName("star_btn")
        self.verticalLayout_3.addWidget(self.star_btn)
        self.finish_btn = QtWidgets.QPushButton(Form)
        self.finish_btn.setObjectName("finish_btn")
        self.verticalLayout_3.addWidget(self.finish_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Автоматизация"))
        self.label.setText(_translate("Form", "Задача запущена"))
        self.label_2.setText(_translate("Form", "Сканируемая папка"))
        self.label_3.setText(_translate("Form", "Папка для сохранения результатов"))
        self.checkBox.setText(_translate("Form", "Сохранять оригинал в подпапке RAW"))
        self.star_btn.setText(_translate("Form", "Запустить задачу"))
        self.finish_btn.setText(_translate("Form", "Остановить задачу"))
