from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(628, 219)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_btn = QtWidgets.QPushButton(Form)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_path = QtWidgets.QLineEdit(Form)
        self.default_path.setObjectName("default_path")
        self.horizontalLayout_2.addWidget(self.default_path)
        self.choose_path_btn = QtWidgets.QPushButton(Form)
        self.choose_path_btn.setObjectName("choose_path_btn")
        self.horizontalLayout_2.addWidget(self.choose_path_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.can_edit = QtWidgets.QCheckBox(Form)
        self.can_edit.setObjectName("can_edit")
        self.verticalLayout_3.addWidget(self.can_edit)
        self.log = QtWidgets.QCheckBox(Form)
        self.log.setObjectName("log")
        self.verticalLayout_3.addWidget(self.log)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.create_preset_btn = QtWidgets.QPushButton(Form)
        self.create_preset_btn.setObjectName("create_preset_btn")
        self.verticalLayout_2.addWidget(self.create_preset_btn)
        self.change_preset_btn = QtWidgets.QPushButton(Form)
        self.change_preset_btn.setObjectName("change_preset_btn")
        self.verticalLayout_2.addWidget(self.change_preset_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.delete_preset_btn = QtWidgets.QPushButton(Form)
        self.delete_preset_btn.setObjectName("delete_preset_btn")
        self.verticalLayout_5.addWidget(self.delete_preset_btn)
        self.presets = QtWidgets.QComboBox(Form)
        self.presets.setObjectName("presets")
        self.verticalLayout_5.addWidget(self.presets)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.cancel_btn.setText(_translate("Form", "Выход"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
        self.label.setText(_translate("Form", "Путь сохранения файлов по умолчанию:"))
        self.choose_path_btn.setText(_translate("Form", "Выбрать"))
        self.can_edit.setText(_translate("Form", "Разрешить ручное редактирования пути"))
        self.log.setText(_translate("Form", "Записывать лог файл"))
        self.create_preset_btn.setText(_translate("Form", "Создать пресет"))
        self.change_preset_btn.setText(_translate("Form", "Изменить пресет"))
        self.delete_preset_btn.setText(_translate("Form", "Удалить выбранный пресет "))
